### ISSUE TITLE
Reporter produces no output if you click the X window close on a flixel app

### ISSUE THREAD

**Issue by 47rooks** [AlexHaxe/haxe-instrument#23]
Running a flixel demo app - the Breakout demo - with these libs.

instrument 1.2
flixel 5.6.2

If I close the window by clicking the X window button the profiler reporter produces no output.
I can, and do, add a key press with a Sys.exit() call which the profiler seems to recognize and then I the reporter runs ok.

**Comment by AlexHaxe** [comment]
instrument tries to figure out when your software calls `Sys.exit` and tries to hook that, so it can do reporting before closing your app. pressing `X` on your window is basically "killing" your app (at least it happens from outside of your Haxe code), so you will have to add some code to catch such an event to allow instrument to perform reporter tasks:
e.g. 
```haxe
		#if instrument
		stage.application.onExit.add(function(e) {
			#if instrument_coverage
			instrument.coverage.Coverage.endCoverage();
			#end
			#if instrument_profiler
			instrument.profiler.Profiler.endProfiler();
			#end
		});
		#end
```
using `#if instrument_profiler` and `#if instrument_coverage` conditionals prevents empty reporter output when iterating between coverage and profiling or both.

a "Quit" button where you exit your software from within your code might also work, but since `X` is always there you might have to hook that anyway cause you are bound to click it while testing :).

**Comment by 47rooks** [comment]
Well there are cleanup hooks from the X - it's not a dirty/crash exit if it's implemented properly. I know where in lime it exits when you close the app. I think the issue here might be that I'm not instrumenting lime. I added lime to the list of instrumented packages and got other errors. I'll open an issue on that.

**Comment by AlexHaxe** [comment]
the issue is not that you didn't instrument lime, it's that `instrument` has no concept of lime or any other library and vice-versa. so if you are using something that has a specific cleanup hook, you need to "help" `instrument` by adding its reporting run to that hook in order to get coverage or profiling output.

**Comment by 47rooks** [comment]
But when I added my own Sys.exit call based on a specific keypress instrument was able to find it without any help. I didn't have to add the kind of code you show above. I was therefore thinking that your heuristics to find Sys.exit calls might also work in lime once instrumented. But my attempt to test that failed - see the other issue. If that doesn't work then sure, I could use the code above, or my own exit routine. Using the code above is probably a cleaner way to exit actually now I think about it.

**Comment by AlexHaxe** [comment]
the reason it worked with your custom `Sys.exit` call is that instrument has a build macro that hooks into `Sys.exit` which adds an `endInstrumentation` call to make sure reporting happens before your program exits:https://github.com/AlexHaxe/haxe-instrument/blob/10244d324710b0e8dba352c731bad4283598bc39/src/instrument/Instrumentation.hx#L132
it's patching the actual `Sys.exit` function, it doesn't try to find all the places where it might be called from. it just goes right to the source.

there might be a way to do the same with lime/openfl/flixel and other frameworks, but I haven't really looked into it. obviously it would be nice if instrument detected and patched all different frameworks it might be used on, so that you didn't have to modify your sources to run coverage or profiling. it would be more seamless and you could just switch it on by using a different .hxml file or enabling it via a `if=` in your project.xml - but someone has to do the detective work first to find the right place to hook into.

**Comment by 47rooks** [comment]
But if that's the case then I don't understand why it didn't work for lime as it calls Sys.exit when you close the window. Unless they are shadowing the exit function. Lime does shadow at least some of haxe, timer I think. Will have to check that.
