### ISSUE TITLE
Profiling macro code

### ISSUE THREAD

**Issue by benmerckx** [AlexHaxe/haxe-instrument#6]
Not sure if this is one of the intended goals (or even possible with macro-in-macro problems) but is there a way to profile code that runs at build time?

**Comment by AlexHaxe** [comment]
instrument uses an init macro to add a build macro to all types which then adds profiling and coverage instrumentation to each function / expression. so during compile time instrument is setting itself up, getting ready to profile, at the same time as other macros do their magic. since there is no guaranteed order in which macros run we cannot be sure that we get first pick. and even then I don't think build macros work on macro classes. 

what you need to be able to profile macros would be something that runs before everything, so a compilation before the compilation or a preprocessor that adds profiling instrumentation before the actual compilation takes place. 

I'm not sure if a compiler plugin would be able to tap into that, however I'm not aware of any such plugin and I probably won't be looking into writing one myself in the near future.

so for now I can only refer you to tools like compiling with `--times -D macro-times`, enabling Haxe server view in VSCode `"haxe.enableServerView": true` or using eval debugger in VSCode to debug your macros.
And of course you can always manually add trace calls to your macros to show progress information during compilation to see where compiler spends most of its time.

**Comment by benmerckx** [comment]
Thanks for the thorough response. I tried setting up the build metadata manually but the compiler catches it :)
````You cannot use @:build inside a macro : make sure that your type is not used in macro````
 I don't think there's a way forward here other than extracting it to run on eval, but it's not very feasible in my case.
For anyone else ending up here, there is Context.timer available: https://github.com/HaxeFoundation/haxe/issues/8814
