### ISSUE TITLE
[neko] Uncaught exception - load.c(398) : Invalid module

### ISSUE THREAD

**Issue by CedX** [AlexHaxe/haxe-instrument#7]
On one of my projects (see https://github.com/cedx/gitea.hx), when the instrumentation is enabled, the [Neko](https://nekovm.org/) tests fail with the error:

`Uncaught exception - load.c(398) : Invalid module : var/tests.n`
(see https://github.com/cedx/gitea.hx/runs/1226877064)

If I disable the instrumentation, the Neko tests succeed.

I'm using `instrument` 1.1.0, and [`utest`](https://lib.haxe.org/p/utest/) 1.13.1 as testing library.
The involved class (the only class that has tests) is:
https://github.com/cedx/gitea.hx/blob/main/src/gitea/DateTools.hx

I've strictly no idea where is the root cause (i.e. in `instrument`, `utest` or the unique dependency: [`datetime`](https://lib.haxe.org/p/datetime/) 3.1.4).

**Comment by AlexHaxe** [comment]
I downloaded your project along with neko sources and ran some tests. it fails loading because a stack check exceeds `MAX_STACK_PER_FUNCTION` of 128. if I up its value to 134 it runs just fine, so it's not some endless recursion. 

I don't know much about neko internals and I haven't found an easy way to figure out what those nested calls are all about. it seems to be in the middle of some Assert call when it hits the limit.
it's very likely related to instrument adding more calls to the mix. not sure if something can be done to reduce nesting though.

I had a similiar error in one of my projects back when I was running munit and mcover tests on neko target. It didn't happen at first, only after some time I couldn't run neko tests anymore - I think I added some tests or changed some code and then suddenly it wouldn't run. so it's not really limited to instrument library. 
I ended up patching neko back then. 
nowadays I stopped using neko target for running tests on that project - it's a PHP project so running neko tests was kinda weird anyway.

**Comment by CedX** [comment]
Thanks for your investigation!
I only use Neko for testing, so it's not a problem for my needs... and I tend to think that most people will instead use a "mainstream" target (i.e. Node.js, PHP, Java, C++, etc.).

As the problem rather comes from Neko: do I keep this issue open?

**Comment by AlexHaxe** [comment]
there is a chance that a thorough investigation would help getting it to run on Neko, because it seems like we only need to shave off a few hierarchy levels. however there are probably other projects where those fixes won't be enough. 
so it's unclear if there's a enough benefit from such work. especially with neko becoming less relevant nowadays.
